version: '3.3'

services:

  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - 8001:8000
    volumes:
      - ./hasker:/src
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web

  postgres:
    image: postgres:10.1-alpine
    build:
      context: db_init
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    container_name: postgres
    ports:
      - 5433:5433
    command: -p 5433
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate && gunicorn hasker.wsgi -w 4 -b 0.0.0.0"
    env_file:
      - .env
    container_name:
      hasker_service
    ports:
      - 8000:8000
    tty: true
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data: