version: '3.3'

services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 8080:8080
      - 80:8080
    volumes:
      - .:/src
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/src/hasker/static/
      - media_volume:/src/hasker/media/
    networks:
      - nginx_network
    depends_on:
      - web

  postgres:
    image: postgres:10.1-alpine
    build:
      context: db_init
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - postgres_network
    env_file:
      - .env
    container_name: postgres
    ports:
      - 5434:5434
    command: -p 5434
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: hasker_service
    volumes:
      - static_volume:/src/hasker/static/
      - media_volume:/src/hasker/media/
    networks:
      - nginx_network
      - postgres_network
    expose:
      - "8080"
    tty: true
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  nginx_network:
    driver: bridge
  postgres_network:
    driver: bridge