version: '3.3'

services:

  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - 8001:8000
    volumes:
      - ./hasker:/src
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web

  postgres:
    image: postgres:10.1-alpine
    build:
      context: db_init
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    container_name: postgres
    ports:
      - 5434:5434
    command: -p 5434
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: hasker_service
    volumes:
      - ./hasker/static:/src/hasker/static
    ports:
      - 8080:8080
    tty: true
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data: